### ISSUE TITLE
[Restaurant]バーマン・客がどこまで対応するか

### ISSUE THREAD

**Issue by ytbilly3636** [RoboCupAtHomeJP/Rule2023#1]
ヒューマンロボットインタラクション（HRI）が生じる時に，人間側がどこまで対応するのか明確に決めておく方が良いと考えています（前回大会のECメンバーの反省会でも本件が反省点として挙がりました）．具体的には，ロボットが注文を取る時と，オブジェクトを渡す時にHRIが発生しますが，ロボットのナビゲーションが中途半端なところで終了した場合に，客がロボットに近づいてインタラクションしても良いかどうかという問題は各トライアルの公平性や採点基準に関わってきます．

例えば次のような方針はいかがでしょうか：客はロボットから指示がない限り椅子からは離れないし椅子も動かさない．ロボットが指示をして客がその指示を理解できればロボットのもとに移動しても良いが，HRIに関わる得点は減点（50%？）する．

TCをはじめ，皆さんからご意見をいただきたく存じます．

**Comment by arata** [comment]
[レストランのドラフトルール](https://github.com/RoboCupAtHomeJP/Rule2023/blob/draft-restaurant/dspl/rules/DSPL/restaurant.md#%E6%8E%A1%E7%82%B9%E6%99%82%E3%81%AE%E6%B3%A8%E6%84%8F)の採点時の注意*2について質問があります．もし，ロボットが人の手の届く範囲に到達しているが，椅子から離れるようにロボットが指示を出しインタラクションが成立した場合当該スコアに0.5をかけますか？　　

というのも，ロボットが到達できないことを考慮してとりあえずロボットが移動し終わったと判断したら，椅子から離れるように指示を出すといったことが考えられると思います．この場合適切なインタラクションとみなすのかというのが問題になるような気がします．　　

また，ペナルティ「オーダーを取る際にクライアントの方向を向いていない」というのは，ロボットが止まった時点で判断するのか，それとも客が椅子から離れてロボットの方向を向いたときにはこのペナルティがか掛かるのかあたりも関係すると思います．

**Comment by arata** [comment]
@ytbilly3636 私も田中さんの上のルールで問題ないと思います．反映よろしくおねがいします．

**Comment by ytbilly3636** [comment]
mainブランチに反映させました．
