### ISSUE TITLE
大会会場のネットワークについて

### ISSUE THREAD

**Issue by hellososhi** [RoboCupAtHomeJP/Rule2023#13]
東京大学TRAILの綱島です。
前回大会では会場で有線と無線のネットワークが提供されたかと思いますが、今大会はどうなる予定でしょうか。
また、会場ネットワークが使えない場合のモバイルルーターの持ち込みに関して、干渉対策などはされる予定でしょうか。
よろしくお願いいたします。

**Comment by arata** [comment]
@hellososhi 
外部ネットワークにつながるwifiアクセスポイントを，DSPLは5GHzが2チャンネル分，OPLは2.4GHz, 5GHzがそれぞれ1チャンネル分ずつ提供される予定です．チームでアクセスポイントを建てることは今大会では禁止されています．

モバイルルータを使用していただくことも可能ですが特に干渉対策はしない予定なので，各チームの自己責任で運用してください．また，モバイルルータを運用する際はwifiを切って，USB接続などの有線接続での使用のみ許可されます．
