### ISSUE TITLE
[OPL/DSPL] Technical Challengeのテーマと得点について

### ISSUE THREAD

**Issue by R2D2-like** [RoboCupAtHomeJP/Rule2023#14]
お世話になっております、東京大学の辻です.

DSPLでのTechnical Challengeのテーマと得点について２点質問があります.
RoboCup@HomeJP2023におけるTechnical Challengeのルールが、
OPLとDSPLでは異なって記載されていたため質問させていただきたいです.

[https://github.com/RoboCupAtHomeJP/Rule2023/blob/main/rules/OPL/tc_ja.md](url)
[https://github.com/RoboCupAtHomeJP/Rule2023/blob/main/rules/DSPL/technical_challenge.md](url)
[https://robocupathome.github.io/RuleBook/rulebook/master.pdf](url)

・テーマ：
OPLと同様に”目標は各チームが自由に設定する”のでしょうか.
それとも、RoboCup2023のRule BookのFinalsに則って、テーマは”The robot helps a person in preparing dinner.”になるのでしょうか.
・得点：
OPLと同様に”競技の得点には反映されず，Technical Challengeは個別に採点・表彰される”のでしょうか.
それとも、RoboCup2023のRule BookのFinalsに則って、DSPLのTechnical Challengeは競技の得点に反映されるのでしょうか.

よろしくお願いいたします.

**Comment by ytbilly3636** [comment]
得点についてはOPLと同様です．Technical Challengeだけが独立します．

テーマについてもOPLと同様に自由に設定して良いというのが私個人の見解です．ただしTCの総意は得ていないので確定ではありません（確認するので少々お待ちください）．

**Comment by ytbilly3636** [comment]
@R2D2-like 確認が遅くなりましたが，テーマはOPLと同様に自由に設定して良いです．よろしくお願い申し上げます．

**Comment by R2D2-like** [comment]
@ytbilly3636 
ありがとうございます！
かしこまりました．
引き続き宜しくお願い致します．
