### ISSUE TITLE
[OPL] Rc デウス・エクス・マキナの減点

### ISSUE THREAD

**Issue by akinobu1998** [RoboCupAtHomeJP/Rule2023#15]
> ホストの特定

部分の減点が明記されていない．

**Comment by MrKeith99** [comment]
> 該当アクションの点数は入らないが，より簡単な手法でアクションをスキップし，タスクを継続することができる

基本的に、デウスエクスマキナを使用すると、減点のではなく、スキップすることができますがその代わりにその部分の点数は0点となります。

**Comment by MrKeith99** [comment]
確かに、ルールには書いていないですね。

**Comment by MrKeith99** [comment]
個人的に、ホストの位置をSetup Dayの時に、公開すればいいと思います。
もし、他チームは点数に反映してほしいという意見があれば、調整してみます。

**Comment by MrKeith99** [comment]
本日のTLM（4月25日）では、「ホストの特定」について以下の結論になりました。

ホストの認識に対する部分タスクは

> 「 紹介中，＿人目のゲストに注意を向ける」

というところに当てはまります。
そのため、デウスエクスマキナを使用する（マーカーなどを使用する）場合、半減します。
