### ISSUE TITLE
[OPL] CMLのナチュラルウォークについて

### ISSUE THREAD

**Issue by OnoFumiya** [RoboCupAtHomeJP/Rule2023#16]
前回のRoboCup Japan Open 2022では、ナチュラルウォークについて振り返りが認められていましたが、今回はどのようになりますか？
前回は、EDUでは振り返りが駄目であったが、OPLでは認められていました。
今回は明確に、振り返りは駄目ということでしょうか？

**Comment by MrKeith99** [comment]
@OnoFumiya さん、本日のTLMでは「ナチュラルウォーク」について話した内容を共有させていただきます。

許容範囲として：
- ロボットの状況を確認するために、振り返えること
- ロボットのペースに合わせて、ゆっくり歩いたり、止まったりすること

許容範囲外：
- ロボットが人を見失ったりしたときに、人間が前の位置に戻ったりすること 
- 明らかに“ナチュラルな行動”でない場合、TCの判断で点数をスコアに追加するか否かが決まる

という風に決まりました。また、「ナチュラルウォーク」について疑問があれば、このissueに追加してください。
