### ISSUE TITLE
[Restaurant]到達をどのように定義するか

### ISSUE THREAD

**Issue by ytbilly3636** [RoboCupAtHomeJP/Rule2023#2]
RCJ22ルールのスコアシートでは「オーダーを取るためにクライアントのテーブルまで移動する」「オーダーを伝えるためにバーマンの元へ戻る」「オブジェクトをデリバリーするためにクライアントのテーブルへ到達する」など，ロボットが到達することで得点が入るものがありました．採点基準を明確にするために，到達を定義しておきたいと思います．

例えば，椅子に座ったクライアントが手を伸ばしてロボット本体に届く距離などはいかがでしょう？

TCをはじめ，皆さんからご意見をいただきたく存じます．

**Comment by arata** [comment]
@ytbilly3636 私も「椅子に座った，または立っているクライアントが手を伸ばしてロボット本体に届く距離」が到達という定義で問題ないと思います．

**Comment by ytbilly3636** [comment]
mainブランチに反映させました．
