### ISSUE TITLE
[DSPL] [OPL] GPSRにおけるオブジェクトの位置の情報

### ISSUE THREAD

**Issue by tsunekazuomija** [RoboCupAtHomeJP/Rule2023#20]
お世話になっております。東京大学TRAILの大見謝です。
RCJ2022のDSPLのGPSRでは各オブジェクトの位置は事前に知らされていましたが、RCJ2023でも同様に事前に知らされるのでしょうか。また事前に公開される場合、いつ頃公開されるか教えていただきたいです。
よろしくお願いいたします。

**Comment by ytbilly3636** [comment]
セットアップデイの間に公開予定です。よろしくお願いします。

**Comment by tsunekazuomija** [comment]
承知いたしました。ご回答ありがとうございます。

**Comment by arata** [comment]
以下のリンクで公開しました．
https://github.com/RoboCupAtHomeJP/AtHome2023/blob/main/DSPL/dspl_objects_with_predefined_location.pdf
