### ISSUE TITLE
[DSPL]事前公開オブジェクト名について

### ISSUE THREAD

**Issue by R2D2-like** [RoboCupAtHomeJP/Rule2023#21]
お世話になっております，東京大学の辻です．
DSPLの事前公開オブジェクトの名前についてです．
8番目のオブジェクトは，Magと記載されていますが，Mugでしょうか？
よろしくお願い致します．
[該当リンク](https://github.com/RoboCupAtHomeJP/AtHome2023/blob/main/DSPL/objects_dspl.pdf)

**Comment by ytbilly3636** [comment]
ありがとうございます。Mugが正しいと思います。ファイルも後ほど修正予定です。

**Comment by R2D2-like** [comment]
ありがとうございます，よろしくお願い致します

**Comment by ytbilly3636** [comment]
修正しました．ついでにラベルも剥がしました．
https://github.com/RoboCupAtHomeJP/AtHome2023/blob/main/DSPL/objects_dspl.pdf
